-
  name: Install and run services
  hosts: prod
  tasks: 
    - name: Install apache2 service
      apt:
          name: apache2
          state: present
      become: yes
  handlers:
    - name: Restart apache2 
      service:
          name: apache2
          state: restarted