--- 
    - name: Install nginx service
      apt:
          name: nginx
          state: present
      become: yes

    - name: nginx service start
      service:
          name: nginx
          state: started
      become: yes

    - name: Deploy web page
      copy:
          src: index.html
          dest: /var/www/html
          remote_src: yes 
      become: yes 
 
