--- 
    - name: Install apache2 service
      apt:
          name: apache2
          state: present
      become: yes

    - name: Install curl service
      apt:
          name: curl
          state: latest
      become: yes